user: chants
services:
  - https://db.r-mes.ovh/ordinaires_2/_design/argos/_rewrite

reservedViewpoints:
- U01 - Indications du Père Jacques Breton
customization:
  use_case: rmes
portfolio:
  chant:
    visitMap: false 


